services:
  openfire:
    image: nasqueron/openfire
    container_name: openfire
    ports:
      - "9090:9090"
      - "9091:9091"
      - "5222:5222"
    volumes:
      - openfire_data:/var/lib/openfire
      - ./openfire_conf/openfire.xml:/etc/openfire/openfire.xml

  # auction-snper:
  #   build:
  #     context: ./auction-sniper  # Ensure this points to the root directory containing your Dockerfile
  #     dockerfile: Dockerfile  # Explicitly specify the Dockerfile if needed
  #   container_name: auction-sniper
  #   depends_on:
  #     - openfire
  #   environment:
  #     - XMPP_SERVER=openfire
  #     - XMPP_PORT=5222

volumes:
  openfire_data:
