/*
 * This source file was generated by the Gradle 'init' task
 */
package org.auction;

import java.net.InetAddress;

import javax.swing.SwingUtilities;

import org.auction.ui.MainWindow;
import org.jivesoftware.smack.chat2.Chat;
import org.jivesoftware.smack.chat2.ChatManager;
import org.jivesoftware.smack.tcp.XMPPTCPConnection;
import org.jivesoftware.smack.tcp.XMPPTCPConnectionConfiguration;
import org.jxmpp.jid.EntityBareJid;
import org.jxmpp.jid.impl.JidCreate;

public class Main {
    private static final int ARG_HOSTNAME = 0;
    private static final int ARG_USERNAME = 1;
    private static final int ARG_PASSWORD = 2;
    private static final int ARG_ITEM_ID = 3;

    private static final String ITEM_ID_AS_LOGIN = "auction-%s";
    private static final String AUCTION_ID_FORMAT = ITEM_ID_AS_LOGIN + "@%s";

    private MainWindow ui;
    private Chat chatNotToBeGCd;

    public Main() throws Exception {
        startUserInterface();
    }

    public static void main(String... args) throws Exception {
        Main main = new Main();
        main.joinAuction(conection(args[ARG_HOSTNAME], args[ARG_USERNAME], args[ARG_PASSWORD]), args[ARG_ITEM_ID]);

    }

    private void joinAuction(XMPPTCPConnection connection, String itemId)
            throws Exception {
        ChatManager chatManager = ChatManager.getInstanceFor(connection);
        chatManager.addIncomingListener((from, message, chat) -> {
            SwingUtilities.invokeLater(() -> {
                ui.showStatus(MainWindow.STATUS_LOST);
            });
        });

        // Create a new chat session with the desired recipient
        EntityBareJid jid = JidCreate.entityBareFrom(auctionId(itemId, connection));
        Chat chat = chatManager.chatWith(jid);
        this.chatNotToBeGCd = chat;
        // Send a message to the recipient
        chat.send("Hello, this is a test message!");
    }

    private static XMPPTCPConnection conection(String hostname, String username, String password)
            throws Exception {
        InetAddress hostAddress = InetAddress.getByName(hostname);
        XMPPTCPConnectionConfiguration config = XMPPTCPConnectionConfiguration.builder()
                .setHostAddress(hostAddress)
                .setXmppDomain(hostname)
                .setUsernameAndPassword(username, password)
                .setSecurityMode(XMPPTCPConnectionConfiguration.SecurityMode.disabled) // Disable security for local
                // development
                .build();
        var connection = new XMPPTCPConnection(config);
        connection.connect();
        connection.login();
        return connection;
    }

    private void startUserInterface() throws Exception {
        SwingUtilities.invokeAndWait(() -> {
            ui = new MainWindow();
        });
    }

    private static String auctionId(String itemId, XMPPTCPConnection connection) {
        return String.format(AUCTION_ID_FORMAT, itemId, connection.getXMPPServiceDomain().toString());
    }
}
